const data = {
            'شاي وقهوة': [
                { id: 11, name: 'شاي أحمد تيباك', weight: 'صغير', price: 1250, img: 'imgs_tea/تيباك احمد صغير.jpg' },
                { id: 2, name: 'شاي ليبتون تيباك', weight: 'صغير', price: 1500, img: 'imgs_tea/تيباك ليبتون صغير.jpg' },
                { id: 3, name: 'شاي محمود تيباك', weight: 'صغير', price: 1250, img: 'imgs_tea/تيباك محمود صغير.jpg' },
                { id: 4, name: 'شاي حسن تيباك', weight: 'صغير', price: 1250, img: 'imgs_tea/تيباك حسن صغير.jpg' },
                { id: 5, name: 'شاي محمود بالهيل', weight: 'تيباك', price: 1250, img: 'imgs_tea/تيباك محمود صغير بالهيل.jpg' },
                { id: 6, name: 'شاي أحمد', weight: '200 غرام', price: 2000, img: 'imgs_tea/احمد 2000.jpg' },
                { id: 7, name: 'شاي عطور', weight: '200 غرام', price: 1750, img: 'imgs_tea/عطور 1750.jpg' },
                { id: 8, name: 'شاي براري', weight: '200 غرام', price: 2000, img: 'imgs_tea/براري 2000.jpg' },
                { id: 9, name: 'شاي حسن', weight: '200 غرام', price: 2000, img: 'imgs_tea/حسن 2000.jpg' },
                { id: 10, name: 'شاي محمود', weight: '200 غرام', price: 2000, img: 'imgs_tea/محمود اسود 2000.jpg' },
                { id: 11, name: 'شاي الوزة', weight: '200 غرام', price: 2000, img: 'imgs_tea/وزة 2000.jpg' },
                { id: 12, name: 'شاي كرك', weight: 'مفرد', price: 250, img: 'imgs_tea/كرك 250.jpg' },
                { id: 13, name: 'قهوة برنس', weight: 'ظرف', price: 1500, img: 'imgs_tea/برنس.jpg' },
                { id: 14, name: 'كابتشينو كودي دايت', weight: 'ظرف', price: 250, img: 'imgs_tea/كودي دايت.jpg' },
                { id: 15, name: 'كابتشينو كودي', weight: 'عادي', price: 250, img: 'imgs_tea/كودي عادي.jpg' },
                { id: 16, name: 'شاي أحمد تيباك', weight: 'كبير', price: 4000, img: 'imgs_tea/تيباك احمد كبير.jpg' },
                { id: 17, name: 'كوكو تيباك', weight: 'باكيت', price: 1500, img: 'imgs_tea/شوكولاته باودر صغير.jpg' },
                { id: 18, name: 'كوكو تيباك', weight: 'كبير', price: 3000, img: 'imgs_tea/شوكولاته باودر وسط.jpg' },
                { id: 19, name: 'قهوة لونا', weight: 'قوطي', price: 1000, img: 'imgs_tea/لونا.jpg' },
                { id: 20, name: 'قهوة كودي', weight: 'بطل', price: 1000, img: 'imgs_tea/كودي بطل.jpg' },
                { id: 21, name: 'قهوة أهواك', weight: 'باكيت', price: 500, img: 'imgs_tea/اهواك.jpg' },
                { id: 22, name: 'حليب أنكور', weight: '400 غرام', price: 4000, img: 'imgs_tea/انكور.jpg' },
                { id: 23, name: 'حليب مدهش', weight: '400 غرام', price: 4000, img: 'imgs_tea/مدهش.jpg' }
            ],
            'معكرونة وشعرية': [
                { id: 9001, name: 'معكرونة كويتيه عكس', weight: 'كيس', price: 1500, img: 'imgs_makrona/معكرونة كويتية عكس.jpg' },
                { id: 9002, name: 'شعرية كويتيه', weight: 'كيس', price: 1500, img: 'imgs_makrona/شعرية كويتية مكسرة.jpg' },
                { id: 9003, name: 'عراقنا الحبيب عكس', weight: 'كيس', price: 1000, img: 'imgs_makrona/عراقنا الحبيب عكس.jpg' },
                { id: 9004, name: 'معكرونة الرؤى برينه', weight: 'كيس', price: 1000, img: 'imgs_makrona/الرؤى برينه.jpg' },
                { id: 9005, name: 'شعرية ملفوفة', weight: 'كيس', price: 500, img: 'imgs_makrona/شعرية ملفوفة.jpg' },
                { id: 9006, name: 'معكرونة زير قلم', weight: 'كيس', price: 1000, img: 'imgs_makrona/زير قلم.jpg' },
                { id: 9007, name: 'معكرونة زير ريكاتي', weight: 'كيس', price: 1000, img: 'imgs_makrona/زير ريكاتي.jpg' },
                { id: 9008, name: 'سباكتي معمورة', weight: 'كيس', price: 500, img: 'imgs_makrona/سباكتي معمورة.jpg' },
                { id: 9009, name: 'معكرونة QAD', weight: 'كيس', price: 250, img: 'imgs_makrona/قاد.jpg' },
                { id: 9010, name: 'مونة شوربة دجاج', weight: 'ظرف', price: 1000, img: 'imgs_makrona/شوربة مونة بالدجاج.jpg' },
                { id: 9011, name: 'مونة شوربة خضار', weight: 'ظرف', price: 1000, img: 'imgs_makrona/شوربة مونة بالخضار.jpg' },
                { id: 9012, name: 'شوربة الين بالدجاج', weight: 'ظرف', price: 500, img: 'imgs_makrona/شوربة الين بالدجاج.jpg' },
                { id: 9013, name: 'شوربة ماجي بالفطر', weight: 'ظرف', price: 1250, img: 'imgs_makrona/شوربة ماجي بالفطر.jpg' },
				{ id: 9014, name: 'شعرية كويتية ملفوفة كبير', weight: 'كيس', price: 1500, img: 'imgs_makrona/شعرية كويتية ملفوفة كبير.jpg' },
				{ id: 9015, name: 'معكرونة كويتية برينه', weight: 'كيس', price: 1500, img: 'imgs_makrona/معكرونة كويتية برينه.jpg' }
				
    ],
            'منظفات سائلة': [
                { id: 5670, name: 'كلور مبيض زيرو', weight: '1000 مل', price: 1500, img: 'imgs_liquid/كلور زيرو 1500.jpg' },
                { id: 5671, name: 'كلور مبيض زيرو', weight: '750 مل', price: 1000, img: 'imgs_liquid/كلور زيرو 1000.jpg' },
                { id: 5672, name: 'كلور مبيض دبة', weight: '4 لتر', price: 4500, img: 'imgs_liquid/كلور زبرو 4500.jpg' },
                { id: 5673, name: 'كلور مبيض صحت', weight: '500 مل', price: 500, img: 'imgs_liquid/كلور صحت 500.jpg' },
                { id: 5674, name: 'مطهر عام زيرو', weight: '500 مل', price: 1000, img: 'imgs_liquid/مطهر زيرو.jpg' },
                { id: 5675, name: 'فلاش زاكس', weight: '1 لتر', price: 1500, img: 'imgs_liquid/فلاش زاكس.jpg' },
                { id: 5676, name: 'زاهي مكين', weight: 'بطل', price: 1000, img: 'imgs_liquid/زاهي مكين.jpg' },
                { id: 5678, name: 'زاهي عملاق', weight: 'بطل', price: 1500, img: 'imgs_liquid/زاهي عملاق 1500.jpg' },
                { id: 5679, name: 'زاهي دينا', weight: 'بطل', price: 2500, img: 'imgs_liquid/زاهي دينا.jpg' },
                { id: 5680, name: 'معطر ارضية عملاق لافندر', weight: 'بطل', price: 2000, img: 'imgs_liquid/عملاق لافندر.jpg' },
                { id: 5681, name: 'فلاش اصلي', weight: 'بطل', price: 3500, img: 'imgs_liquid/no.jpg' },
                { id: 5682, name: 'زاهي O2 ', weight: '3 لتر', price: 3000, img: 'imgs_liquid/no.jpg' },
                { id: 5683, name: 'جل عملاق', weight: 'علبة صغيرة', price: 1500, img: 'imgs_liquid/جل عملاق 1500.jpg' },
                { id: 5684, name: 'جل عملاق', weight: 'علبة كبيرة', price: 2500, img: 'imgs_liquid/no.jpg' },
                { id: 5685, name: 'معطر ارضية عملاق ورد', weight: 'بطل', price: 2000, img: 'imgs_liquid/عملاق ورد.jpg' },
                { id: 5686, name: 'معطر ارضية عملاق بوكيه', weight: 'بطل', price: 2000, img: 'imgs_liquid/عملاق بوكيه.jpg' },
                { id: 5687, name: 'معطر ارضية عملاق ياسمين', weight: 'بطل', price: 2000, img: 'imgs_liquid/عملاق ياسمين.jpg' },
                { id: 5688, name: 'صابون مكين بالفواكه', weight: 'بطل', price: 1500, img: 'imgs_liquid/مكين فواكه.jpg' },
                { id: 5689, name: 'صابون مكين بالزيتون', weight: 'بطل', price: 1500, img: 'imgs_liquid/مكين زيتون.jpg' },
                { id: 5690, name: 'منظف اثاث واسطح المطبخ', weight: 'بخاخ', price: 2500, img: 'imgs_liquid/تنظيف اخشاب.jpg' },
                { id: 5691, name: 'جل استحمام ذهبي', weight: 'بطل', price: 4000, img: 'imgs_liquid/جل استحمام ذهبي.jpg' },
                { id: 5692, name: 'سائل غسيل للملابس السوداء', weight: 'بطل', price: 2000, img: 'imgs_liquid/سلطان سوداء.jpg' },
                { id: 5693, name: 'ABC لملابس الاطفال', weight: 'بطل', price: 4000, img: 'imgs_liquid/ABC للاطفال.jpg' },
                { id: 5694, name: 'ABC للملابس البيضاء', weight: 'بطل', price: 4000, img: 'imgs_liquid/ABC بيضاء.jpg' },
                { id: 5695, name: 'ABC للملابس الحساسة والصوفية', weight: 'بطل', price: 4000, img: 'imgs_liquid/ABC حساسة.jpg' },
                { id: 5696, name: 'ABC لكافة انواع الملابس', weight: 'بطل', price: 4000, img: 'imgs_liquid/ABC ملون.jpg' }
            
    ],
           'رز': [
                { id: 1001, name: 'ملك البنجاب 900 غرام', weight: '900 غرام', price: 2500, img: 'imgs_liquid/.jpg' },
                { id: 1002, name: 'افندي 900 غرام', weight: '900 غرام', price: 2000, img: 'imgs_liquid/.jpg' },
                { id: 1003, name: 'دينار 900 غرام', weight: '900 غرام', price: 2000, img: 'imgs_liquid/.jpg' },
                { id: 1004, name: 'هيرتج 900 غرام', weight: '900 غرام', price: 2500, img: 'imgs_liquid/.jpg' },
                { id: 1005, name: 'بشاور الذهب 900 غرام', weight: '900 غرام', price: 2500, img: 'imgs_liquid/.jpg' },
                { id: 1006, name: 'اهلنا 900 غرام', weight: '900 غرام', price: 2500, img: 'imgs_liquid/.jpg' },
                { id: 1007, name: 'اهلنا 4.5 كيلو', weight: '4.5 كيلو', price: 12000, img: 'imgs_liquid/.jpg' }
				
	],
				
			'مخبوزات': [
                { id: 1110, name: 'خبز لبناني المطاحن الكويتية', weight: 'كيس', price: 1000, img: 'imgs_bread/.jpg' },
                { id: 1111, name: 'افندي 900 غرام', weight: '900 غرام', price: 2000, img: 'imgs_bread/.jpg' },
                { id: 1112, name: 'دينار 900 غرام', weight: '900 غرام', price: 2000, img: 'imgs_bread/.jpg' },
                { id: 1113, name: 'هيرتج 900 غرام', weight: '900 غرام', price: 2500, img: 'imgs_bread/.jpg' }
                
    ],
            
            'شوكولاته':  [
                { id: 3001, name: 'سنيكرز Original', weight: 'قطعة', price: 750, img: 'imgs_chocolate/no.jpg' },
                { id: 3003, name: 'سنيكرز موس ماراكوجا', weight: 'قطعة', price: 750, img: 'imgs_chocolate/b3.jpg' },
                { id: 3004, name: 'مارس', weight: 'قطعة', price: 750, img: 'imgs_chocolate/b2.jpg' },
                { id: 3005, name: 'ريسيز', weight: 'قطعة', price: 1500, img: 'imgs_chocolate/b5.jpg' },
                { id: 3006, name: 'كيندر 4 اصابع', weight: 'قطعة', price: 1250, img: 'imgs_chocolate/b6.jpg' },
                { id: 3007, name: 'باونتي', weight: 'قطعة', price: 750, img: 'imgs_chocolate/no.jpg' },
                { id: 3008, name: 'فلير', weight: 'قطعة', price: 1500, img: 'imgs_chocolate/b9.jpg' },
                { id: 3011, name: 'كيندر اصبع', weight: 'قطعة', price: 500, img: 'imgs_chocolate/.jpg' },
                { id: 3012, name: 'داريلو بالكاراميل', weight: 'قطعة', price: 500, img: 'imgs_chocolate/.jpg' },
                { id: 3013, name: 'داريلو بجوز الهند', weight: 'قطعة', price: 500, img: 'imgs_chocolate/.jpg' },
                { id: 3014, name: 'Roso lips', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3015, name: 'ميلودي', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3016, name: 'اريزونا حبيبات بسكويت', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3017, name: 'شوكو بريك', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3018, name: '4*4', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3019, name: 'son soz', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3020, name: 'سوداني', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3021, name: 'كومبو', weight: 'قطعة', price: 500, img: 'imgs_chocolate/b8.jpg' }
            ],
            'نستلة': [
                { id: 3101, name: 'نمبر وان احمر', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b13.jpg' },
                { id: 3102, name: 'نمبر وان اخضر', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b12.jpg' },
                { id: 3103, name: 'مستر بايت بندق', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b11.jpg' },
                { id: 3104, name: 'ويف اب كاكاو', weight: 'قطعة', price: 250, img: 'imgs_chocolate/no.jpg' },
                { id: 3105, name: 'شوكتو تريبس', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b16.jpg' },
                { id: 3106, name: 'كات كات كاكاو', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b15.jpg' },
                { id: 3107, name: 'GO UP توت', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b23.jpg' },
                { id: 3108, name: 'GO UP كاكاو داكن', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b22.jpg' }
            ],
            'كيك': [
                { id: 3201, name: 'باب الاغا كاكاو', weight: 'قطعة', price: 250, img: 'imgs_chocolate/no.jpg' },
                { id: 3202, name: 'باب الاغا سادة', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b19.jpg' },
                { id: 3203, name: 'تايني', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b17.jpg' },
                { id: 3204, name: 'لوبو', weight: 'قطعة', price: 250, img: 'imgs_chocolate/no.jpg' },
                { id: 3205, name: 'كرواسون شيبابا', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b24.jpg' },
                { id: 3206, name: 'اوتي بركر كاكاو', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b29.jpg' },
                { id: 3207, name: 'بريك فاست فانيلا', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b25.jpg' },
                { id: 3208, name: 'اوتي بركر كراميل', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b30.jpg' },
                { id: 3209, name: 'اوتي بركر فانيلا', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b32.jpg' },
                { id: 3210, name: 'باب الاغا فراولة', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b27.jpg' },
                { id: 3211, name: 'coco cake', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b26.jpg' },
                { id: 3212, name: 'بوند بالزبدة', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3213, name: 'كاسة شوكولاته', weight: 'قطعة', price: 250, img: 'imgs_chocolate/.jpg' },
                { id: 3214, name: 'Raisin بالكشمش', weight: 'قطعة', price: 250, img: 'imgs_chocolate/b31.jpg' }
            ],
            'غازيات': [
                { id: 401, name: 'بيبسي رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/pepsi250.jpg' },
                { id: 402, name: 'سفن رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/7up250.jpg' },
                { id: 403, name: 'شاني رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/shani250.jpg' },
                { id: 404, name: 'ميرندا رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/mirinda250.jpg' },
                { id: 405, name: 'حمضيات رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/mirinda250green.jpg' },
                { id: 406, name: 'كولا رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/cola250.jpg' },
                { id: 407, name: 'كولا دايت رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/cola250zero.jpg' },
                { id: 408, name: 'ديو رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/dew250.jpg' },
                { id: 422, name: 'فانتا برتقال رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/fanta250mirinda.jpg' },
                { id: 423, name: 'فانتا كرز رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/fanta250shani.jpg' },
                { id: 424, name: 'فانتا تفاح رفيع', weight: '150 مل', price: 250, img: 'imgs_gaz/fanta250apple.jpg' },
                { id: 425, name: 'سبرايت رفيع أخضر', weight: '150 مل', price: 250, img: 'imgs_gaz/sprite250green.jpg' },
                { id: 426, name: 'سبرايت رفيع أزرق', weight: '150 مل', price: 250, img: 'imgs_gaz/sprite250blue.jpg' },
                { id: 409, name: 'بيبسي وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/pepsi500.jpg' },
                { id: 410, name: 'شاني وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/shani500.jpg' },
                { id: 411, name: 'ديو وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/dew500.jpg' },
                { id: 412, name: 'سفن أب وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/7up500.jpg' },
                { id: 413, name: 'ميرندا وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/mirinda500.jpg' },
                { id: 414, name: 'حمضيات وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/mirinda500green.jpg' },
                { id: 415, name: 'كولا وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/cola500.jpg' },
                { id: 416, name: 'كولا دايت وسط', weight: '330 مل', price: 500, img: 'imgs_gaz/cola500zero.jpg' },
                { id: 427, name: 'سبرايت وسط أخضر', weight: '330 مل', price: 500, img: 'imgs_gaz/sprite500green.jpg' },
                { id: 428, name: 'سبرايت وسط أزرق', weight: '330 مل', price: 500, img: 'imgs_gaz/sprite500blue.jpg' },
                { id: 429, name: 'فانتا وسط برتقال', weight: '330 مل', price: 500, img: 'imgs_gaz/fanta500mirinda.jpg' },
                { id: 501, name: 'بيبسي جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/pepsi750.jpg' },
                { id: 502, name: 'شاني جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/shani750.jpg' },
                { id: 503, name: 'ميرندا جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/mirinda750.jpg' },
                { id: 504, name: 'ديو جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/dew750.jpg' },
                { id: 505, name: 'سفن أب جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/7up750.jpg' },
                { id: 506, name: 'كولا جوال', weight: '750 مل', price: 750, img: 'imgs_gaz/cola750.jpg' },
                { id: 507, name: 'بيبسي لتر', weight: '1 لتر', price: 1000, img: 'imgs_gaz/pepsi1000.jpg' },
                { id: 508, name: 'شاني لتر', weight: '1 لتر', price: 1000, img: 'imgs_gaz/shani1000.jpg' },
                { id: 509, name: 'سفن أب لتر', weight: '1 لتر', price: 1000, img: 'imgs_gaz/7up1000.jpg' },
                { id: 510, name: 'ديو لتر', weight: '1 لتر', price: 1000, img: 'imgs_gaz/dew1000.jpg' },
                { id: 511, name: 'كولا عائلية', weight: '1.75 لتر', price: 1250, img: 'imgs_gaz/cola1250.jpg' },
                { id: 417, name: 'بيبسي زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/pepsi500glass.jpg' },
                { id: 418, name: 'ميرندا زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/mirinda500glass.jpg' },
                { id: 419, name: 'سفن زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/7up500glass.jpg' },
                { id: 420, name: 'ديو زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/dew500glass.jpg' },
                { id: 421, name: 'كولا زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/cola500glass.jpg' },
                { id: 422, name: 'سبرايت زجاج', weight: 'زجاج', price: 500, img: 'imgs_gaz/spriteglass.jpg' },
                { id: 423, name: 'كولا بلاستك', weight: 'بطل', price: 250, img: 'imgs_gaz/كولا بلاستك 250.jpg' },
				{ id: 424, name: 'سبرايت بلاستك', weight: 'بطل', price: 250, img: 'imgs_gaz/سبرايت بلاستك 250.jpg' },
				{ id: 425, name: 'سنابل شعير ليمون', weight: 'علبة', price: 500, img: 'imgs_gaz/سنابل شعير ليمون 500.jpg' },
				{ id: 426, name: 'سنابل شعير فراولة', weight: 'علبة', price: 500, img: 'imgs_gaz/سنابل شعير فراولة 500.jpg' },
				{ id: 427, name: 'سنابل شعير تفاح', weight: 'علبة', price: 500, img: 'imgs_gaz/سنابل شعير تفاح 500.jpg' },
				{ id: 428, name: 'مالت شعير سادة', weight: 'علبة', price: 500, img: 'imgs_gaz/مالت شعير سادة 500.jpg' },
				{ id: 429, name: 'دايموند ليمون', weight: 'زجاج', price: 250, img: 'imgs_gaz/دايموند ليمون.jpg' },
				{ id: 430, name: 'دايموند فواكه', weight: 'زجاج', price: 250, img: 'imgs_gaz/دايموند فواكه.jpg' },
				{ id: 431, name: 'دايموند مشمش', weight: 'زجاج', price: 250, img: 'imgs_gaz/دايموند مشمش.jpg' },
				{ id: 432, name: 'بربيكان فراولة', weight: 'علبة', price: 500, img: 'imgs_gaz/بربيكان فراولة 500.jpg' },
				{ id: 433, name: 'بربيكان اناناس', weight: 'علبة', price: 500, img: 'imgs_gaz/بربيكان اناناس 500.jpg' }
            ],
            'معلبات غذائية': [
                { id: 2001, name: 'دولمة بالليمون', weight: 'علبة', price: 3000, img: 'imgs_m3lbat/m1.jpg' },
                { id: 2002, name: 'دولمة بدبس الرمان', weight: 'علبة', price: 3000, img: 'imgs_m3lbat/m2.jpg' },
                { id: 2003, name: 'دولمة بزيت الزيتون', weight: 'علبة', price: 3000, img: 'imgs_m3lbat/m3.jpg' },
                { id: 2004, name: 'صوصج لحم بقري', weight: 'علبة', price: 2000, img: 'imgs_m3lbat/m4.jpg' },
                { id: 2005, name: 'لونشون لحم بقري', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m5.jpg' },
                { id: 2006, name: 'بوردون مثروم الاصلي', weight: 'علبة', price: 3000, img: 'imgs_m3lbat/m6.jpg' },
                { id: 2007, name: 'بوردون لونشون لحم', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m7.jpg' },
                { id: 2008, name: 'بوردون لونشون دجاج', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m8.jpg' },
                { id: 2009, name: 'لونشون لحم صغير', weight: 'صغير', price: 500, img: 'imgs_m3lbat/m9.jpg' },
                { id: 2010, name: 'لونشون دجاج صغير', weight: 'صغير', price: 500, img: 'imgs_m3lbat/m10.jpg' },
                { id: 2011, name: 'مرق بامية', weight: 'علبة', price: 2000, img: 'imgs_m3lbat/m11.jpg' },
                { id: 2012, name: 'مرق فاصوليا', weight: 'علبة', price: 2000, img: 'imgs_m3lbat/m12.jpg' },
                { id: 2013, name: 'مرق قيمة النجفية', weight: 'علبة', price: 2000, img: 'imgs_m3lbat/m13.jpg' },
                { id: 2014, name: 'مرق باذنجان', weight: 'علبة', price: 2000, img: 'imgs_m3lbat/m14.jpg' },
                { id: 2015, name: 'حميسة بالفطر Silvana', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m15.jpg' },
                { id: 2016, name: 'يخني خضروات', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m16.jpg' },
                { id: 2017, name: 'مخلمة Delveseh', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m17.jpg' },
                { id: 2018, name: 'حميسة أصالت', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m18.jpg' },
                { id: 2019, name: 'قلية الخضروات', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m19.jpg' },
                { id: 2020, name: 'مخلمة Silvana', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m20.jpg' },
                { id: 2021, name: 'بزاليا بجزر', weight: 'علبة', price: 750, img: 'imgs_m3lbat/m21.jpg' },
                { id: 2022, name: 'فول ليزا', weight: 'علبة', price: 500, img: 'imgs_m3lbat/m22.jpg' },
                { id: 2023, name: 'بزاليا بجزر الرائد', weight: 'علبة', price: 750, img: 'imgs_m3lbat/m23.jpg' },
                { id: 2024, name: 'بزاليا', weight: 'علبة', price: 750, img: 'imgs_m3lbat/m24.jpg' },
                { id: 2025, name: 'فول الطازج كبير', weight: 'كبير', price: 1000, img: 'imgs_m3lbat/m25.jpg' },
                { id: 2026, name: 'فول الرائد', weight: 'علبة', price: 750, img: 'imgs_m3lbat/m26.jpg' },
                { id: 2027, name: 'حمص', weight: 'علبة', price: 750, img: 'imgs_m3lbat/m27.jpg' },
                { id: 2028, name: 'فطر مقطع', weight: 'علبة', price: 1250, img: 'imgs_m3lbat/m28.jpg' },
                { id: 2029, name: 'زيتون مقطع', weight: 'علبة', price: 1250, img: 'imgs_m3lbat/m29.jpg' },
                { id: 2030, name: 'ذرة ابو الورد', weight: 'علبة', price: 1000, img: 'imgs_m3lbat/m30.jpg' },
                { id: 2031, name: 'فواكه مشكلة كبير', weight: 'كبير', price: 3500, img: 'imgs_m3lbat/m31.jpg' },
                { id: 2032, name: 'صدر دجاج معلب', weight: 'علبة', price: 1500, img: 'imgs_m3lbat/m32.jpg' },
                { id: 2033, name: 'تونة مفتتة بالفلفل', weight: 'علبة', price: 1250, img: 'imgs_m3lbat/m33.jpg' },
                { id: 2034, name: 'تونة بركة بالماء', weight: 'علبة', price: 1500, img: 'imgs_m3lbat/m34.jpg' },
                { id: 2035, name: 'تونة نواجل كبير', weight: 'كبير', price: 3750, img: 'imgs_m3lbat/m35.jpg' },
                { id: 2036, name: 'تونة مفتتة بارد', weight: 'علبة', price: 1250, img: 'imgs_m3lbat/m36.jpg' },
                { id: 2037, name: 'تونة هوسم بالفلفل', weight: 'علبة', price: 1500, img: 'imgs_m3lbat/m37.jpg' },
                { id: 2038, name: 'تونة بركة بالزيت', weight: 'علبة', price: 1500, img: 'imgs_m3lbat/m38.jpg' },
                { id: 2039, name: 'تونة نازك بالفلفل', weight: 'علبة', price: 1500, img: 'imgs_m3lbat/m39.jpg' },
                { id: 2040, name: 'حمص زجاج', weight: 'زجاج', price: 1500, img: 'imgs_m3lbat/m40.jpg' },
                { id: 2041, name: 'فاصوليا زجاج', weight: 'زجاج', price: 1500, img: 'imgs_m3lbat/m41.jpg' },
                { id: 2042, name: 'كاكاو زجاج', weight: 'زجاج', price: 1000, img: 'imgs_m3lbat/m42.jpg' }
            ],
             'شيبس': [
                { id: 2011, name: 'بوشار تغاريد', weight: 'كيس', price: 250, img: 'imgs_chips/بوشار تغاريد.jpg' },
                { id: 2012, name: 'شامية بالزبدة', weight: 'كيس', price: 250, img: 'imgs_chips/شامية باندا.jpg' },
                { id: 2013, name: 'البنفسج بالبصل', weight: 'كيس', price: 250, img: 'imgs_chips/البنفسج.jpg' },
                { id: 2014, name: 'لوسي برتقالي', weight: 'كيس', price: 250, img: 'imgs_chips/لوسي برتقالي.jpg' },
                { id: 2015, name: 'لوسي اخضر ', weight: 'كيس', price: 250, img: 'imgs_chips/لوسي اخضر.jpg' },
                { id: 2016, name: 'فواز', weight: 'كيس', price: 250, img: 'imgs_chips/فواز.jpg' },
                { id: 2017, name: 'مانشيز اصابع', weight: 'كيس', price: 250, img: 'imgs_chips/مانشيز اصابع.jpg' },
                { id: 2018, name: 'نايس جبن صغير', weight: 'كيس', price: 250, img: 'imgs_chips/نايس جبن 250.jpg' },
                { id: 2019, name: 'دانا سمايل', weight: 'كيس', price: 250, img: 'imgs_chips/ابو الوجه.jpg' },
                { id: 2020, name: 'نايس اعشاب وسط', weight: 'كيس', price: 500, img: 'imgs_chips/نايس اعشاب 500.jpg' },
                { id: 2021, name: 'نايس جبن وسط', weight: 'كيس', price: 500, img: 'imgs_chips/نايس جبن 500.jpg' },
                { id: 2022, name: 'نايس خل وسط', weight: 'كيس', price: 500, img: 'imgs_chips/نايس خل 500.jpg' },
                { id: 2023, name: 'جوانة', weight: 'كيس', price: 250, img: 'imgs_chips/جوانة.jpg' },
                { id: 2024, name: 'ماركو حار', weight: 'كيس', price: 250, img: 'imgs_chips/ماركو حار.jpg' },
                { id: 2025, name: 'ماكس جبن وسط', weight: 'كيس', price: 500, img: 'imgs_chips/ماكس جبن 500.jpg' },
                { id: 2026, name: 'ليز كاتشب وسط', weight: 'كيس', price: 500, img: 'imgs_chips/ليز كاتشب 500.jpg' },
                { id: 2027, name: 'ليز اصلي وسط', weight: 'كيس', price: 500, img: 'imgs_chips/no.jpg' },
                { id: 2028, name: 'دوريتوس حار حلو وسط', weight: 'كيس', price: 500, img: 'imgs_chips/دوريتوس ازرق 500.jpg' },
                { id: 2029, name: 'ليز خل وملح وسط', weight: 'كيس', price: 500, img: 'imgs_chips/ليز خل 500.jpg' },
                { id: 2030, name: 'ماكس مشاوي وسط', weight: 'كيس', price: 500, img: 'imgs_chips/ماكس مشاوي 500.jpg' },
                { id: 2031, name: 'ليز جبن وسط', weight: 'كيس', price: 500, img: 'imgs_chips/ليز جبن 500.jpg' },
                { id: 2032, name: 'ليز كاتشب صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ليز كاتشب 250.jpg' },
                { id: 2033, name: 'ماكس حار صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ماكس حار 250.jpg' },
                { id: 2034, name: 'دوريتوس حار حلو صغير', weight: 'كيس', price: 250, img: 'imgs_chips/دوريتوس ازرق 250.jpg' },
                { id: 2035, name: 'ليز جبن صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ليز جبن 250.jpg' },
                { id: 2036, name: 'ماكس جبن صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ماكس جبن 250.jpg' },
                { id: 2037, name: 'ليز اعشاب صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ليز اعشاب 250.jpg' },
                { id: 2038, name: 'ماكس مشاوي صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ماكس مشاوي 250.jpg' },
                { id: 2039, name: 'ماكس اعشاب صغير', weight: 'كيس', price: 250, img: 'imgs_chips/ماكس اعشاب 250.jpg' },
                { id: 2040, name: 'ليز جبن كبير', weight: 'كيس', price: 1000, img: 'imgs_chips/ليز جبن 1000.jpg' },
				{ id: 2041, name: 'برنكلز حار صغير', weight: 'علبة', price: 1250, img: 'imgs_chips/برنكلز حار صغير.jpg' },
				{ id: 2042, name: 'برنكلز جبن صغير', weight: 'علبة', price: 1250, img: 'imgs_chips/برنكلز جبن صغير.jpg' },
				{ id: 2043, name: 'برنكلز بابريكا صغير', weight: 'علبة', price: 1250, img: 'imgs_chips/ليز جبن 1000.jpg' },
				{ id: 2044, name: 'ستاكس جبن', weight: 'علبة', price: 750, img: 'imgs_chips/ستاكس جبن.jpg' },
				{ id: 2045, name: 'ستاكس اعشاب', weight: 'علبة', price: 750, img: 'imgs_chips/ستاكس اعشاب.jpg' }
            ],
			
			'لحوم مجمدة':  [
                { id: 3101, name: 'دجاج ساديا 1100', weight: 'قطعة', price: 5500, img: 'imgs_freez/no.jpg' },
                { id: 3103, name: 'ناجتس دجاج بالجبنة ساديا', weight: 'قطعة', price: 3000, img: 'imgs_freez/b3.jpg' },
                { id: 3104, name: 'صدر دجاج مقرمش ساديا', weight: 'قطعة', price: 3000, img: 'imgs_freez/b2.jpg' },
                { id: 3105, name: 'صوصج دجاج بالجبنة ساديا', weight: 'قطعة', price: 2000, img: 'imgs_freez/b5.jpg' },
                { id: 3106, name: 'صوصج دجاج عادي ساديا', weight: 'قطعة', price: 2000, img: 'imgs_freez/b6.jpg' },
				{ id: 3107, name: 'اصابع دجاج مقرمشة ساديا', weight: 'قطعة', price: 4000, img: 'imgs_freez/b6.jpg' },
				{ id: 3108, name: 'ستيك صدر دجاج ساديا', weight: 'قطعة', price: 1000, img: 'imgs_freez/b6.jpg' },
                { id: 3109, name: 'صدر دجاج ساديا 450غ', weight: 'قطعة', price: 3500, img: 'imgs_freez/no.jpg' },
                { id: 3110, name: 'كرسبي جيكور', weight: 'قطعة', price: 4500, img: 'imgs_freez/b9.jpg' },
                { id: 3111, name: 'كبة مرق جيكور', weight: 'قطعة', price: 3000, img: 'imgs_freez/.jpg' },
                { id: 3112, name: 'كبة سندويج صغير جيكور', weight: 'قطعة', price: 2500, img: 'imgs_freez/.jpg' },
                { id: 3113, name: 'كبة برغل جيكور', weight: 'قطعة', price: 3000, img: 'imgs_freez/.jpg' },
                { id: 3114, name: 'كبة موصلية بالدجاج وسط جيكور', weight: 'قطعة', price: 4000, img: 'imgs_freez/.jpg' },
                { id: 3115, name: 'خبز صاج تركي', weight: 'قطعة', price: 2500, img: 'imgs_freez/.jpg' },
                { id: 3116, name: 'فلافل جيكور', weight: 'قطعة', price: 2500, img: 'imgs_freez/.jpg' },
                { id: 3117, name: 'برجر دجاج جيكور', weight: 'قطعة', price: 3000, img: 'imgs_freez/.jpg' },
                { id: 3118, name: 'برجر لحم جيكور', weight: 'قطعة', price: 3000, img: 'imgs_freez/.jpg' },
                { id: 3119, name: 'فنكر تركي مرسين', weight: 'قطعة', price: 3500, img: 'imgs_freez/.jpg' },
                { id: 3120, name: 'فنكر ايراني', weight: 'قطعة', price: 2500, img: 'imgs_freez/.jpg' },
                { id: 3121, name: 'خبز سمبوسة', weight: 'قطعة', price: 1750, img: 'imgs_freez/b8.jpg' },
				{ id: 3122, name: 'فلافل جيكور', weight: 'قطعة', price: 2500, img: 'imgs_freez/.jpg' },
                { id: 3123, name: 'جبن موزريلا مرسين', weight: 'قطعة', price: 3500, img: 'imgs_freez/.jpg' },
                { id: 3124, name: 'لحم مثروم جيكور', weight: 'قطعة', price: 4000, img: 'imgs_freez/.jpg' }
				
			],
            
            'سكائر': [
                { id: 101, name: 'ماستر ابيض', weight: 'باكيت', price: 1250, img: 'imgs_smoke/ماستر ابيض.jpg' },
                { id: 102, name: 'ماستر رصاصي', weight: 'باكيت', price: 750, img: 'imgs_smoke/ماستر رصاصي.jpg' },
                { id: 103, name: 'ميلانو', weight: 'باكيت', price: 750, img: 'imgs_smoke/ميلانو.jpg' },
                { id: 104, name: 'كنت توت', weight: 'باكيت', price: 1500, img: 'imgs_smoke/كنت توت.jpg' },
                { id: 105, name: 'كنت رقم 1', weight: 'باكيت', price: 1500, img: 'imgs_smoke/كنت 1.jpg' },
                { id: 106, name: 'كنت رقم 4', weight: 'باكيت', price: 1500, img: 'imgs_smoke/كنت 4.jpg' },
                { id: 107, name: 'ايسي رصاصي', weight: 'باكيت', price: 1750, img: 'imgs_smoke/ايسي رصاصي.jpg' },
                { id: 108, name: 'ايسي نعناع طويل', weight: 'باكيت', price: 1500, img: 'imgs_smoke/ايسي ازرق طويل.jpg' },
                { id: 109, name: 'ايسي اسود', weight: 'باكيت', price: 1500, img: 'imgs_smoke/ايسي اسود.jpg' },
                { id: 110, name: 'ام تي توت', weight: 'باكيت', price: 1000, img: 'imgs_smoke/ام تي توت.jpg' },
                { id: 111, name: 'ام تي نعناع', weight: 'باكيت', price: 1000, img: 'imgs_smoke/ام تي نعناع.jpg' },
                { id: 112, name: 'ام تي علكة', weight: 'باكيت', price: 1000, img: 'imgs_smoke/ام تي علكة.jpg' },
                { id: 113, name: 'كلواز اصفر', weight: 'باكيت', price: 1000, img: 'imgs_smoke/كلواز.jpg' },
                { id: 114, name: 'مارلبورو رفيع ابيض', weight: 'باكيت', price: 1500, img: 'imgs_smoke/مارلبورو ابيض.jpg' },
                { id: 115, name: 'مارلبورو مضلع ابيض', weight: 'باكيت', price: 2000, img: 'imgs_smoke/مارلبورو ابيض مضلع.jpg' },
                { id: 116, name: 'مارلبورو رفيع ازرق', weight: 'باكيت', price: 1500, img: 'imgs_smoke/مارلبورو ازرق.jpg' },
                { id: 117, name: 'اوسكار رصاصي', weight: 'باكيت', price: 500, img: 'imgs_smoke/اوسكار رصاصي.jpg' },
                { id: 118, name: 'ماك عادي', weight: 'باكيت', price: 500, img: 'imgs_smoke/ماك عادي.jpg' },
                { id: 119, name: 'ماك نعناع', weight: 'باكيت', price: 750, img: 'imgs_smoke/ماك نعناع.jpg' },
                { id: 120, name: 'ايسي نعناع صغير', weight: 'باكيت', price: 2000, img: 'imgs_smoke/ايسي ازرق قصير.jpg' },
                { id: 121, name: 'ايسي نعناع مضلع', weight: 'باكيت', price: 1500, img: 'imgs_smoke/ايسي ازرق مضلع.jpg' },
                { id: 122, name: 'موند تفاح', weight: 'باكيت', price: 750, img: 'imgs_smoke/موند تفاح.jpg' },
                { id: 123, name: 'معسل تفاحتين مصري', weight: 'باكيت', price: 1500, img: 'imgs_smoke/تفاحتين.jpg' },
                { id: 124, name: 'معسل نعناع', weight: 'باكيت', price: 1500, img: 'imgs_smoke/نعناع.jpg' },
                { id: 125, name: 'معسل انكليزي', weight: 'باكيت', price: 1500, img: 'imgs_smoke/انجليزي.jpg' },
                { id: 126, name: 'معسل ليمون', weight: 'باكيت', price: 1500, img: 'imgs_smoke/ليمون.jpg' }
            ],
            'صلصة': [
                { id: 9101, name: 'شطة ديك اصلي', weight: 'بطل', price: 1000, img: 'imgs_salsa/n3.jpg' },
                { id: 9102, name: 'شطة صغيرة', weight: 'بطل', price: 500, img: 'imgs_salsa/n4.jpg' },
                { id: 9103, name: 'شطة كبيرة', weight: 'بطل', price: 1000, img: 'imgs_salsa/n6.jpg' },
                { id: 9104, name: 'صلصة ريزو', weight: 'بطل', price: 2500, img: 'imgs_salsa/n5.jpg' },
                { id: 9105, name: 'صاص العربي', weight: 'بطل', price: 1000, img: 'imgs_salsa/n7.jpg' },
                { id: 9106, name: 'دبس الرمان', weight: 'صغير', price: 1000, img: 'imgs_salsa/n8.jpg' },
				{ id: 9107, name: 'مايونيز تيفاني تصلي', weight: 'علبة', price: 2500, img: 'imgs_salsa/مايونيز تيفاني اصلي.jpg' },
				{ id: 9108, name: 'مايونيز تيفاني باربكيو', weight: 'علبة', price: 2500, img: 'imgs_salsa/مايونيز تيفاني باربكيو.jpg' },
				{ id: 9109, name: 'مايونيز بالثوم كاله', weight: 'علبة', price: 2250, img: 'imgs_salsa/مايونيز بالثوم كاله.jpg' },
				{ id: 9110, name: 'صلصة باربكيو كاله', weight: 'علبة', price: 1250, img: 'imgs_salsa/صلصة باربكيو كاله.jpg' },
				{ id: 9112, name: 'عجينة تندوري صلصة', weight: 'علبة', price: 3500, img: 'imgs_salsa/عجينة تندوري.jpg' },
				{ id: 9113, name: 'معجون جارام ماسالا', weight: 'علبة', price: 3500, img: 'imgs_salsa/معجون جارام ماسالا.jpg' },
				{ id: 9114, name: 'شطة ديك اصلي كبير', weight: 'علبة', price: 3500, img: 'imgs_salsa/شطة ديك اصلي كبير.jpg' },
				{ id: 9115, name: 'شطة رنا سعودية', weight: 'علبة', price: 1000, img: 'imgs_salsa/شطة رنا سعودية.jpg' }
				
            ],
            'معجون طماطم': [
                { id: 9001, name: 'التونسا', weight: 'كبير', price: 2500, img: 'imgs_salsa/n11.jpg' },
                { id: 9002, name: 'عراقنا الحبيب', weight: 'وسط', price: 1000, img: 'imgs_salsa/n10.jpg' },
                { id: 9003, name: 'KDD', weight: 'علبة', price: 1500, img: 'imgs_salsa/n9.jpg' },
                { id: 9004, name: 'الرياض صغير', weight: 'علبة', price: 500, img: 'imgs_salsa/alriadh500.jpg' },
                { id: 9005, name: 'الرياض وسط', weight: 'علبة', price: 1000, img: 'imgs_salsa/alriadh1000.jpg' }
            ],
            'اندومي': [
                { id: 8001, name: 'اندومي خضار', weight: 'كيس', price: 250, img: 'imgs_indome/indome250green.jpg' },
                { id: 8002, name: 'اندومي دجاج بلدي', weight: 'كيس', price: 250, img: 'imgs_indome/indome250chiken.jpg' },
                { id: 8003, name: 'اندومي دجاج بالكاري', weight: 'كيس', price: 250, img: 'imgs_indome/indome250kare.jpg' },
                { id: 8004, name: 'اندومي دجاج نكهة خاصة', weight: 'كيس', price: 250, img: 'imgs_indome/.jpg' },
                { id: 8005, name: 'اندومي قدح دجاج', weight: 'قدح', price: 500, img: 'imgs_indome/indome500.jpg' },
                { id: 8006, name: 'اندومي قدح دجاج', weight: 'قدح كبير', price: 750, img: 'imgs_indome/indome750chiken.jpg' },
                { id: 8007, name: 'اندومي قدح خضار', weight: 'قدح كبير', price: 750, img: 'imgs_indome/indome750green.jpg' }
            ], 
            'عصائر': [
                { id: 1001, name: 'بلو دانه برتقال', weight: '250 مل', price: 250, img: 'imgs_aser/dana250orange.jpg' },
                { id: 1002, name: 'بلو دانه مانجو', weight: '250 مل', price: 250, img: 'imgs_aser/dana250mango.jpg' },
                { id: 1003, name: 'بلو دانه فواكه', weight: '250 مل', price: 250, img: 'imgs_aser/dana250frote.jpg' },
                { id: 1004, name: 'دادا برتقال', weight: '250 مل', price: 250, img: 'imgs_aser/dada250orange.jpg' },
                { id: 1005, name: 'دادا فراولة وتوت', weight: '250 مل', price: 250, img: 'imgs_aser/no.jpg' },
                { id: 1006, name: 'دادا موز وفواولة', weight: '250 مل', price: 250, img: 'imgs_aser/no.jpg' },
                { id: 1007, name: 'دادا مانجو', weight: '250 مل', price: 250, img: 'imgs_aser/dada250mango.jpg' },
                { id: 1008, name: 'دادا لومي بصرة', weight: '250 مل', price: 250, img: 'imgs_aser/dada250lome.jpg' },
                { id: 1009, name: 'دادا فواكه', weight: '250 مل', price: 250, img: 'imgs_aser/dada250frote.jpg' },
                { id: 1010, name: 'دادا رمان', weight: '250 مل', price: 250, img: 'imgs_aser/no.jpg' },
                { id: 1011, name: 'رند برتقال', weight: '500 مل', price: 500, img: 'imgs_aser/rend500orange.jpg' },
                { id: 1012, name: 'رند ليمون ونعناع', weight: '500 مل', price: 500, img: 'imgs_aser/rend500lemon.jpg' },
                { id: 1013, name: 'رند موز وفواولة', weight: '500 مل', price: 500, img: 'imgs_aser/rend500banana.jpg' },
                { id: 1014, name: 'رند رمان', weight: '500 مل', price: 500, img: 'imgs_aser/rend500rman.jpg' },
                { id: 1015, name: 'رند عنب', weight: '500 مل', price: 500, img: 'imgs_aser/rend5003nb.jpg' },
                { id: 1016, name: 'رند ليمون', weight: '500 مل', price: 500, img: 'imgs_aser/rend500lemon2.jpg' },
                { id: 1017, name: 'رند مشمش', weight: '500 مل', price: 500, img: 'imgs_aser/rend500mshmsh.jpg' },
                { id: 1018, name: 'تانج اناناس باودر', weight: '1 later', price: 500, img: 'imgs_aser/tangananas.jpg' },
                { id: 1019, name: 'تانج ليمون باودر', weight: '1 later', price: 500, img: 'imgs_aser/tanglemon.jpg' },
                { id: 1020, name: 'توت باودر', weight: '1 later', price: 250, img: 'imgs_aser/iraqunatoot.jpg' },
                { id: 1021, name: 'ليمون باودر', weight: '1 later', price: 250, img: 'imgs_aser/iraqunalemon.jpg' },
                { id: 1022, name: 'تمر هند باودر', weight: '1 later', price: 250, img: 'imgs_aser/iraqunahinde.jpg' },
                { id: 1023, name: 'مانجو باودر', weight: '1 later', price: 250, img: 'imgs_aser/iraqunamango.jpg' },
                { id: 1024, name: 'راني برتقال', weight: 'علبة', price: 500, img: 'imgs_aser/راني برتقال 500.jpg' },
				{ id: 1024, name: 'راني اناناس وجوز هند', weight: 'علبة', price: 500, img: 'imgs_aser/راني اناناس وجوز هند 500.jpg' },
				{ id: 1024, name: 'راني خوخ اناناس برتقال', weight: 'علبة', price: 250, img: 'imgs_aser/راني خوخ اناناس برتقال 500.jpg' },
				{ id: 1024, name: 'راني موز وفراولة', weight: 'علبة', price: 500, img: 'imgs_aser/راني موز وفراولة 500.jpg' }

				
            ],
            'مخللات': [
                { id: 9201, name: 'خل ابيض', weight: 'بطل', price: 1000, img: 'imgs_salsa/n13.jpg' },
                { id: 9202, name: 'خل تفاح', weight: 'بطل', price: 1000, img: 'imgs_salsa/n12.jpg' },
                { id: 9203, name: 'خل العربي', weight: 'وسط', price: 1000, img: 'imgs_salsa/n14.jpg' },
                { id: 9204, name: 'خل العربي', weight: 'كبير', price: 1500, img: 'imgs_salsa/n15.jpg' },
                { id: 9205, name: 'خل صغير', weight: 'صغير', price: 500, img: 'imgs_salsa/n100.jpg' },
                { id: 9206, name: 'خل تفاح عضوي', weight: 'علبة', price: 4000, img: 'imgs_salsa/n103.jpg' },
                { id: 9207, name: 'ليمون', weight: 'بطل', price: 1000, img: 'imgs_salsa/n104.jpg' },
                { id: 9208, name: 'مخلل مانجو', weight: 'علبة', price: 2500, img: 'imgs_salsa/n2.jpg' },
                { id: 9209, name: 'عمبة مانجو', weight: 'بطل', price: 2500, img: 'imgs_salsa/n1.jpg' },
				{ id: 9210, name: 'مخلل جمل حار', weight: 'علبة', price: 2500, img: 'imgs_salsa/مخلل جمل حار.jpg' },
				{ id: 9211, name: 'طرشي ليمون حار', weight: 'علبة', price: 3500, img: 'imgs_salsa/طرشي ليمون حار.jpg' }
            ],
           'بهارات': [
                { id: 7001, name: 'فلفل احمر', weight: 'علبة', price: 1000, img: 'imgs_bharat/flflred.jpg' },
                { id: 7002, name: 'فلفل اسود', weight: 'علبة', price: 1250, img: 'imgs_bharat/flflblack.jpg' },
                { id: 7003, name: 'بصل مطحون', weight: 'علبة', price: 1000, img: 'imgs_bharat/basal.jpg' },
                { id: 7004, name: 'بهارات دجاج', weight: 'علبة', price: 1000, img: 'imgs_bharat/chiken.jpg' },
                { id: 7005, name: 'بابريكا', weight: 'علبة', price: 1000, img: 'imgs_bharat/babreka.jpg' },
                { id: 7006, name: 'بهارات شاورما لحم', weight: 'علبة', price: 1000, img: 'imgs_bharat/shawrma.jpg' },
                { id: 7007, name: 'بهارات كبة', weight: 'علبة', price: 1000, img: 'imgs_bharat/kuba.jpg' },
                { id: 7008, name: 'خلطة سبع بهارات', weight: 'علبة', price: 1000, img: 'imgs_bharat/7.jpg' },
                { id: 7009, name: 'بهارات فنكر', weight: 'علبة', price: 1000, img: 'imgs_bharat/finger.jpg' },
                { id: 7010, name: 'بهارات جدر', weight: 'علبة', price: 1000, img: 'imgs_bharat/gder.jpg' },
                { id: 7011, name: 'قرنفل', weight: 'علبة', price: 1000, img: 'imgs_bharat/grnful.jpg' },
                { id: 7012, name: 'زنجبيل', weight: 'علبة', price: 1000, img: 'imgs_bharat/zngabel.jpg' },
                { id: 7013, name: 'دارسين', weight: 'علبة', price: 1000, img: 'imgs_bharat/darsen.jpg' },
                { id: 7014, name: 'كزبرة', weight: 'علبة', price: 1000, img: 'imgs_bharat/kuzbra.jpg' },
                { id: 7015, name: 'نعناع', weight: 'علبة', price: 1000, img: 'imgs_bharat/n3na3.jpg' },
                { id: 7016, name: 'بهارات لحم مشوي', weight: 'علبة', price: 1000, img: 'imgs_bharat/mashawe.jpg' },
                { id: 7017, name: 'هيل', weight: 'علبة', price: 250, img: 'imgs_bharat/hail.jpg' },
                { id: 7018, name: 'كاري', weight: 'علبة', price: 250, img: 'imgs_bharat/kare.jpg' }
            ],
            'جبن': [
                { id: 7001, name: 'صباح كرات', weight: 'علبة', price: 1250, img: 'imgs_alban/sabahball.jpg' },
                { id: 7002, name: 'جبن شرائح', weight: 'قطعة', price: 500, img: 'imgs_alban/taste.jpg' },
                { id: 7003, name: 'كنوز شيدر', weight: 'علبة', price: 1000, img: 'imgs_alban/knoz.jpg' },
                { id: 7004, name: 'صباح مالح', weight: 'علبة', price: 1250, img: 'imgs_alban/sabahsalt.jpg' }, 
                { id: 7005, name: 'بف صغير', weight: 'صغير', price: 500, img: 'imgs_alban/bafsmall.jpg' },
                { id: 7006, name: 'بف كبير', weight: 'علبة', price: 1500, img: 'imgs_alban/bafbig.jpg' },
                { id: 7007, name: 'قيمر كي دي دي', weight: 'علبة', price: 500, img: 'imgs_alban/kddkshta.jpg' },
                { id: 7008, name: 'صباح لبنة', weight: 'علبة', price: 1500, img: 'imgs_alban/sabahlabna.jpg' },
                { id: 7009, name: 'صباح عرب', weight: 'قطعة', price: 1500, img: 'imgs_alban/sabaharab.jpg' },
                { id: 7010, name: 'كيري صغير', weight: 'صغير', price: 1000, img: 'imgs_alban/kirismall.jpg' },
                { id: 7011, name: 'كرافت صغير', weight: 'صغير', price: 1500, img: 'imgs_alban/kraftsmall.jpg' },
                { id: 7012, name: 'كرافت كبير', weight: 'كبير', price: 2500, img: 'imgs_alban/kraftbig.jpg' },
                { id: 7013, name: 'ابو الولد مثلث', weight: 'باكيت', price: 1500, img: 'imgs_alban/aboalwalad.jpg' },
                { id: 7014, name: 'قيمر نجود', weight: 'قطعة', price: 500, img: 'imgs_alban/njod.jpg' },
                { id: 7015, name: 'قيمر كالة', weight: 'قطعة', price: 500, img: 'imgs_alban/kala.jpg' },
                { id: 7016, name: 'مراعي صغير شيدر', weight: 'قطعة', price: 1500, img: 'imgs_alban/maraismallgold.jpg' },
                { id: 7017, name: 'كيري وسط 6 قطع', weight: 'وسط', price: 2500, img: 'imgs_alban/kirimedil.jpg' },
                { id: 7018, name: 'كيبي وسط 6 قطع', weight: 'وسط', price: 1500, img: 'imgs_alban/kibimedil.jpg' },
                { id: 7019, name: 'بوك زجاجي', weight: 'وسط', price: 3000, img: 'imgs_alban/puck.jpg' },
                { id: 7020, name: 'مراعي وسط', weight: 'وسط', price: 2500, img: 'imgs_alban/maraimedilblue.jpg' },
                { id: 7021, name: 'مراعي صغير', weight: 'صغير', price: 1500, img: 'imgs_alban/maraismallblue.jpg' },
                { id: 7022, name: 'فونك ', weight: 'وسط', price: 2000, img: 'imgs_alban/vonkmedil.jpg' },
                { id: 7023, name: 'كيري عائلي*24', weight: '24 قطعة', price: 7500, img: 'imgs_alban/kiribigbig.jpg' },
                { id: 7024, name: 'صباح مالح قوطي', weight: 'علبة', price: 1250, img: 'imgs_alban/sabahsaltwhite.jpg' },
                { id: 7025, name: 'جبنة شيدر لوكس', weight: 'علبة', price: 500, img: 'imgs_alban/lux.jpg' },
                { id: 7026, name: 'زبدة معجنات', weight: 'قطعة', price: 500, img: 'imgs_alban/zbda.jpg' },
                { id: 7027, name: 'جبنة بالقشطة سليمانية', weight: 'علبة', price: 500, img: 'imgs_alban/slemani.jpg' },
                { id: 7028, name: 'شيدر اليما', weight: 'قطعة', price: 500, img: 'imgs_alban/alima.jpg' },
                { id: 7029, name: 'لنبة ايراني', weight: 'قطعة', price: 500, img: 'imgs_alban/labna.jpg' },
                { id: 7030, name: 'جبنة البقرة سليمانية', weight: 'قطعة', price: 500, img: 'imgs_alban/slemaniblue.jpg' }
            ],
            'لبن': [
                { id: 3201, name: 'لبن الامير سادة', weight: 'قطعة', price: 250, img: 'imgs_laban/الامير سادة 250.jpg' },
                { id: 3202, name: 'لبن الامير ليمون', weight: 'قطعة', price: 250, img: 'imgs_laban/الامير ليمون 250.jpg' },
                { id: 3203, name: 'لبن الامير نعناع', weight: 'قطعة', price: 250, img: 'imgs_laban/الامير نعناع 250.jpg' },
                { id: 3204, name: 'لبن الامير مدخن', weight: 'قطعة', price: 250, img: 'imgs_laban/الامير مدخن 250.jpg' },
                { id: 3205, name: 'لبن دوغ', weight: 'قطعة', price: 500, img: 'imgs_laban/لبن دوغ 500.jpg' },
                { id: 3206, name: 'لبن جياو', weight: 'قطعة', price: 500, img: 'imgs_laban/لبن جياو 500.jpg' },                     
                { id: 3207, name: 'زبادي سطل', weight: 'قطعة', price: 1750, img: 'imgs_laban/زبادي سطل.jpg' },
                { id: 3208, name: 'زبادي مانيزان وسط', weight: 'قطعة', price: 1000, img: 'imgs_laban/زبادي مانيزان 1000.jpg' },
                { id: 3209, name: 'زبادي الامير صغير', weight: 'قطعة', price: 250, img: 'imgs_laban/زبادي الامير 250.jpg' },
                { id: 3210, name: 'جاموس ايراني', weight: 'قطعة', price: 1000, img: 'imgs_laban/جاموس ايراني 1000.jpg' },
                { id: 3211, name: 'سفن دبة', weight: 'قطعة', price: 4000, img: 'imgs_laban/سفن دبة 4000.jpg' },                        
                { id: 3212, name: 'زبادي كالة صغير', weight: 'قطعة', price: 500, img: 'imgs_laban/زبادي كالة 500.jpg' }                        
            ],
            'حليب': [
                { id: 1201, name: 'حليب فراولة', weight: 'باكيت', price: 750, img: 'imgs_milk/حليب كي دي دي فراولة 500.jpg' },         
                { id: 1202, name: 'حليب موز', weight: 'باكيت', price: 750, img: 'imgs_milk/حليب كي دي دي موز 500.jpg' },
                { id: 1203, name: 'حليب شوكولاته', weight: 'باكيت', price: 750, img: 'imgs_milk/حليب كي دي دي شوكولاته 500.jpg' },
                { id: 1204, name: 'حليب سادة', weight: 'باكيت', price: 750, img: 'imgs_milk/حليب كي دي دي ابيض 500.jpg' },
                { id: 1205, name: 'حليب سعودية شوكولاته', weight: 'باكيت', price: 500, img: 'imgs_milk/حليب سعودية شوكولاته.jpg' },
                { id: 1206, name: 'حليب فراولة', weight: 'باكيت', price: 250, img: 'imgs_milk/حليب كي دي دي فراولة 250.jpg' }			
			
			],
            'بسكويت': [
                { id: 6001, name: 'فرخنده دايت دارسين وتفاح', weight: 'باكيت', price: 1000, img: 'imgs_bskt/farkhndaapple.jpg' },
                { id: 6002, name: 'فرخندة دايت كاكاو', weight: 'باكيت', price: 1000, img: 'imgs_bskt/farkhndacoco.jpg' },
                { id: 6003, name: 'بسكويت ليدي فينغرز دايت', weight: 'علبة', price: 3000, img: 'imgs_bskt/bsktdiet.jpg' },
                { id: 6004, name: 'باف باستري بالكرز', weight: 'علبة', price: 3000, img: 'imgs_bskt/bsktokrane.jpg' },
                { id: 6005, name: 'كوكيز ايراني', weight: 'باكيت', price: 1000, img: 'imgs_bskt/kokez1000.jpg' },
                { id: 6006, name: 'بسكويت اليوم بالموز', weight: 'قطعة', price: 250, img: 'imgs_bskt/todaybanana.jpg' },
                { id: 6007, name: 'بسكت بالجبن', weight: 'قطعة', price: 250, img: 'imgs_bskt/bsktjubn.jpg' },
                { id: 6008, name: 'بسكويت مالح', weight: 'قطعة', price: 250, img: 'imgs_bskt/bsktsalt.jpg' },
                { id: 6009, name: 'بسكت لونا', weight: 'قطعة', price: 250, img: 'imgs_bskt/bsktluna.jpg' },
                { id: 6010, name: 'بسكت بوك', weight: 'قطعة', price: 250, img: 'imgs_bskt/bsktbook.jpg' },
                { id: 6011, name: 'بسكت بالكاكاو', weight: 'قطعة', price: 250, img: 'imgs_bskt/bsktcoco.jpg' },
                { id: 6012, name: 'بسكت توركو بالكاكاو', weight: 'قطعة', price: 250, img: 'imgs_bskt/torkococo.jpg' },
                { id: 6013, name: 'بسكت اولكر بالفانيلا', weight: 'قطعة', price: 250, img: 'imgs_bskt/torkowhite.jpg' },
                { id: 6014, name: 'بسكت هايد سيك', weight: 'قطعة', price: 500, img: 'imgs_bskt/hideseek.jpg' },
                { id: 6015, name: 'بسكت اولكر بالفراولة', weight: 'قطعة', price: 250, img: 'imgs_bskt/ulkerfrawla.jpg' },
                { id: 6016, name: 'بسكت توركو بالموز', weight: 'قطعة', price: 250, img: 'imgs_bskt/torkobanana.jpg' },
                { id: 6017, name: 'بسكت اولكر بالموز', weight: 'قطعة', price: 250, img: 'imgs_bskt/ulkerbanana.jpg' },
                { id: 6018, name: 'اوريو وسط', weight: 'قطعة', price: 500, img: 'imgs_bskt/no.jpg' },
                { id: 6019, name: 'كوكيز بالكاكاو', weight: 'قطعة', price: 250, img: 'imgs_bskt/kokez250.jpg' },
                { id: 6020, name: 'كوكيز بجوز الهند', weight: 'قطعة', price: 250, img: 'imgs_bskt/kokezblue.jpg' },
                { id: 6021, name: 'بسكت شعير', weight: 'قطعة', price: 250, img: 'imgs_bskt/shaaer.jpg' },
                { id: 6022, name: 'كوكيز بالزبدة', weight: 'قطعة', price: 250, img: 'imgs_bskt/kokezzbda.jpg' },
                { id: 6023, name: 'اوريو صغير', weight: 'قطعة', price: 250, img: 'imgs_bskt/oreo250.jpg' }
            ],
           
		    'جلاتين': [],
		   
		   
  		    'شامبو': [
                
                { id: 1211, name: 'شامبو هيد اند شولدرز بالنعناع', weight: 'علبة', price: 4500, img: 'imgs_shampo/k9blue.jpg' },         
                { id: 1212, name: 'شامبو هيد اند شولدرز بالفحم', weight: 'علبة', price: 4500, img: 'imgs_shampo/k9red.jpg' },
                { id: 1214, name: 'شامبو ايبك', weight: 'علبة', price: 500, img: 'imgs_shampo/k9yellow.jpg' },
                { id: 1215, name: 'شامبو اطفال', weight: 'علبة', price: 1500, img: 'imgs_shampo/k9purpel.jpg' },
                { id: 1216, name: 'شامبو كلير الازرق', weight: 'علبة', price: 5000, img: 'imgs_shampo/aspirshred.jpg' },
                { id: 1217, name: 'شامبو كلير الابيض', weight: 'علبة', price: 5000, img: 'imgs_shampo/tiger.jpg' }
            ],
			
			'بقوليات': [
                { id: 8101, name: 'عدس', weight: '500 غرام', price: 1250, img: 'imgs_bkoliat/عدس.jpg' },
                { id: 8102, name: 'ذرة شامية', weight: '500 غرام', price: 1000, img: 'imgs_bkoliat/ذرة شامية.jpg' },
                { id: 8103, name: 'فاصوليا', weight: '500 غرام', price: 1500, img: 'imgs_bkoliat/فاصوليا.jpg' },
                { id: 8104, name: 'جريش', weight: '500 غرام', price: 1000, img: 'imgs_bkoliat/جريش.jpg' },
                { id: 8105, name: 'برغل ناعم', weight: '500 غرام', price: 1000, img: 'imgs_bkoliat/برغل ناعم.jpg' },
                { id: 8106, name: 'برغل خشن', weight: '500 غرام', price: 1000, img: 'imgs_bkoliat/برغل خشن.jpg' },
                { id: 8107, name: 'برغل بالشعرية', weight: '500 غرام', price: 1000, img: 'imgs_bkoliat/برغل بالشعرية.jpg' }
				 ],
        
  		    'طاقة': [
                
                { id: 1200, name: 'k9 اخضر', weight: 'علبة', price: 500, img: 'imgs_power/k9 اخضر.jpg' },         
                { id: 1201, name: 'K9 احمر', weight: 'علبة', price: 500, img: 'imgs_power/k9red.jpg' },
                { id: 1202, name: 'K9 اصفر', weight: 'علبة', price: 500, img: 'imgs_power/k9yellow.jpg' },
                { id: 1203, name: 'K9 وردي', weight: 'علبة', price: 500, img: 'imgs_power/k9purpel.jpg' },
                { id: 1204, name: 'اسبي رش احمر', weight: 'علبة', price: 500, img: 'imgs_power/aspirshred.jpg' },
                { id: 1205, name: 'تايگر', weight: 'علبة', price: 1000, img: 'imgs_power/tiger.jpg' }
            ],
			
            'مواد غذائية': [
			
			    { id: 9011, name: ' خميرة فورية صغيرة', weight: 'كيس', price: 500, img: 'imgs_mawad/خميرة سريعة.jpg' },
                { id: 9012, name: 'بيكنج باودر 2', weight: 'كيس', price: 250, img: 'imgs_mawad/بيكنج باودر.jpg' },
                { id: 9013, name: 'فانيلا 2', weight: 'كيس', price: 250, img: 'imgs_mawad/فانيلا.jpg' },
                { id: 9014, name: 'سكر 1 كيلو', weight: 'كيس', price: 1250, img: 'imgs_mawad/سكر.jpg' },
                { id: 9015, name: 'كشمش ربع كيلو', weight: 'كيس', price: 2000, img: 'imgs_mawad/كشمش.jpg' },
                { id: 9016, name: 'حوز هند مبروش', weight: 'كيس', price: 500, img: 'imgs_mawad/جوز هند مبروش.jpg' },
                { id: 9017, name: 'زيتون زير اسود', weight: 'علبة', price: 1250, img: 'imgs_mawad/زيتون زير اسود.jpg' },
                { id: 9018, name: 'زيتون زير اخضر', weight: 'علبة', price: 1500, img: 'imgs_mawad/زيتون زير اخضر.jpg' },
                { id: 9019, name: 'ملح زارا وسط', weight: 'كيس', price: 500, img: 'imgs_mawad/ملح زارا 500.jpg' },
                { id: 9020, name: 'ملح زارا 2.5 كيلو', weight: 'كيس', price: 1500, img: 'imgs_mawad/ملح زارا 1500.jpg' },
                { id: 9021, name: 'ملح صغير', weight: 'كيس', price: 250, img: 'imgs_mawad/ملح 250.jpg' },
                { id: 9022, name: 'تمر سيف نبوت', weight: 'كيس', price: 3000, img: 'imgs_mawad/تمر سيف نبوت سعودي.jpg' },
                { id: 9023, name: 'عجينة تمر كليجة', weight: 'كيس', price: 2000, img: 'imgs_mawad/عجينة تمر للكليجة.jpg' },
                { id: 9024, name: 'مربى الطازج فراولة', weight: 'زجاج', price: 1500, img: 'imgs_mawad/مربى الطازج فراولة.jpg' },
                { id: 9025, name: 'مربى الطازج مشمش', weight: 'زجاج', price: 1500, img: 'imgs_mawad/مربى الطازج مشمش.jpg' },
                { id: 9026, name: 'مربى سيمرة مشمش', weight: 'علبة', price: 1000, img: 'imgs_mawad/مربى سيمرة مشمش.jpg' },
                { id: 9027, name: 'مربى سيمرة جزر', weight: 'علبة', price: 1000, img: 'imgs_mawad/مربى سيمرة بالجزر.jpg' },
                { id: 9028, name: 'مربى سيمرة تين', weight: 'علبة', price: 1000, img: 'imgs_mawad/مربى سيمرة تين.jpg' }
		
		],
            'مكسرات': [
                { id: 8001, name: 'فستق صغير', weight: 'كيس', price: 250, img: 'imgs_muksrat/fustk250.jpg' },
                { id: 8002, name: 'حب ابيض صغير', weight: 'كيس', price: 250, img: 'imgs_muksrat/white250.jpg' },
                { id: 8003, name: 'لوز صغير', weight: 'كيس', price: 250, img: 'imgs_muksrat/loz250.jpg' },
                { id: 8004, name: 'كاجو صغير', weight: 'كيس', price: 250, img: 'imgs_muksrat/kajo250.jpg' },
                { id: 8005, name: 'حب شمس صغير', weight: 'كيس', price: 250, img: 'imgs_muksrat/shams250.jpg' },
                { id: 8006, name: 'مخلط وسط', weight: 'كيس', price: 500, img: 'imgs_muksrat/mukhalat500.jpg' },
                { id: 8007, name: 'فستق وسط', weight: 'كيس', price: 1000, img: 'imgs_muksrat/fuskt1000.jpg' },
                { id: 8008, name: 'حب ابيض كبير', weight: 'كيس', price: 1000, img: 'imgs_muksrat/white1000.jpg' },
                { id: 8009, name: 'مخلط كبير', weight: 'كيس', price: 1000, img: 'imgs_muksrat/mukhalat1000.jpg' },
                { id: 8010, name: 'حب شمس كبير', weight: 'كيس', price: 1000, img: 'imgs_muksrat/shams1000.jpg' },
                { id: 8011, name: 'مكسرات عائلي', weight: 'كيس كبير', price: 2500, img: 'imgs_muksrat/mukhalat2500.jpg' },
                { id: 8012, name: 'كاجو عائلي', weight: 'كيس كبير', price: 2500, img: 'imgs_muksrat/kajo2500.jpg' }
            ],
            'زيت وسمن نباتي': [
		     	{ id: 8011, name: 'زيت الدار ', weight: '900 مل', price: 2500, img: 'imgs_oil/زيت الدار 900 مل.jpg' },
                { id: 8012, name: 'زيت زيتون الطازج', weight: 'زجاج', price: 2500, img: 'imgs_oil/زيت زيتون الطازج 2500.jpg' },
                { id: 8013, name: 'سمن نباتي جنة', weight: '700 غرام', price: 3500, img: 'imgs_oil/دهن جنة.jpg' },
                { id: 8014, name: 'سمن نباتي دلال الكويتي', weight: '1 كيلو', price: 4000, img: 'imgs_oil/دهن دلال 4000.jpg' },
                { id: 8015, name: 'سمن نباتي دلال الكويتي', weight: '2 كيلو', price: 7500, img: 'imgs_oil/دهن دلال 7500.jpg' },
				{ id: 8011, name: 'زيت الدار ', weight: '900 مل', price: 2500, img: 'imgs_oil/زيت الدار 1 لتر.jpg' }
				],
            
        };
